"""add_knowledge_chunks_table

Revision ID: 8fd11c9afbc0
Revises: 
Create Date: 2026-02-05 18:52:39.060481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd11c9afbc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('machinery_id', sa.String(length=50), nullable=True),
    sa.Column('part_name', sa.String(length=100), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_machinery_id'), ['machinery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_source_type'), ['source_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_source_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_machinery_id'))

    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
